# Site settings
<<<<<<< HEAD
title: Peter Briggs
email: pacbriggs@gmail.com
url: www.peterabriggs.com
description: "Showcasing the past video projects of Peter Briggs, this site is a portfolio giving a look into the work of an aspiring videographer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Peter Briggs
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pbriggin
  - title: facebook
    url: https://www.facebook.com/peter.briggs.796
  - title: google plus
    url: https://plus.google.com/u/0/
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/pbriggin

# Postal address (add as many lines as necessary)
address:
  - line: 3517 Ramsgate Ct
  - line: Lexington Kentucky, 40503

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
=======
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/freelancer-theme"
>>>>>>> FETCH_HEAD

# Build settings
markdown: kramdown
permalink: pretty
